version: '3.8'
services:
  mysql_celeb_match:
    container_name: mysql_celeb_match
    image: 'mysql:8.0.19'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=celeb_match
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Database/celebs.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:
