###
POST http://127.0.0.1:8000/predict
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="upload_file"; filename="test_celeb7.jpg"
Content-Type: image/jpeg

< test/test_celeb7.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://127.0.0.1:8000/lookalike
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="upload_file"; filename="test_celeb1.jpg"
Content-Type: image/jpeg

< test/test_celeb1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Test search API
POST http://127.0.0.1:8000/search
Content-Type: application/json

{
  "gender": "MALE",
  "songs": [
    "Giải thưởng Làn Sóng Xanh - Ca khúc của năm 2022: Đoạt giải (See tình)",
    "Giải thưởng Mai Vàng - Ca khúc được yêu thích nhất 2019: Đoạt giải (Để Mị nói cho mà nghe)"
  ],
  "awards": []
}

